seed: 42
num_workers: auto # 0 when using from Windows 
num_classes: 11
class_list:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
batch_size: 16
n_epochs: 8
scheduler: ReduceLROnPlateau
scheduler_params:
  StepLR:
    step_size: 2
    gamma: 0.3
    last_epoch: -1
    verbose: True
  ReduceLROnPlateau:
    mode: max
    factor: 0.7
    patience: 2
    threshold: 0.01
    threshold_mode: rel
    cooldown: 0
    min_lr: 1.e-5
    eps: 1.e-8
    verbose: True
  CosineAnnealingWarmRestarts:
    T_0: 10
    T_mult: 1
    eta_min: 0
    last_epoch: -1
    verbose: True    
train_step_scheduler: False
val_step_scheduler: True
optimizer: AdamW
optimizer_params:
  AdamW:
    lr: 1.e-3
    betas:
      - 0.9
      - 0.999
    eps: 1.e-8
    weight_decay: 1.e-3
    amsgrad: False
  Adam:
    lr: 1.e-4
    betas:
      - 0.9
      - 0.999
    eps: 1.e-8
    weight_decay: 1.e-6
    amsgrad: False
criterion_train: BCEWithLogitsLoss
criterion_val: BCEWithLogitsLoss
criterion_params:
  CrossEntropyLoss:
    weight: null
    size_average: null
    ignore_index: -100
    reduce: null
    reduction: mean
  LabelSmoothingLoss:
    classes: 2
    smoothing: 0.05
    dim: -1
  FocalCosineLoss:
    alpha: 1
    gamma: 2
    xent: 0.1
use_amp: True
debug: True
cv_schema: RepeatedStratifiedGroupKFold
result_params:
  average_loss: {}
  multi_class_roc_auc_score: {}
  val_preds_softmax_array: {}
results_train:
  - average_loss
results_val:
  - average_loss
  - val_preds_softmax_array
  - multi_class_roc_auc_score
monitored_result: multi_class_roc_auc_score
image_size: 256
verbose: 1
verbose_step: 1
num_folds: 5
image_col_name: StudyInstanceUID
class_col_name:
  - ETT - Abnormal
  - ETT - Borderline
  - ETT - Normal
  - NGT - Abnormal
  - NGT - Borderline
  - NGT - Incompletely Imaged
  - NGT - Normal
  - CVC - Abnormal
  - CVC - Borderline
  - CVC - Normal
  - Swan Ganz Catheter Present
group_kfold_split: PatientID
paths:
  log_path: /content/drive/My Drive/RANZCR/weights/resnet_200D/6th-Mar-V1/log.txt
  train_path: /content/train/train
  csv_path: /content/df_folds.csv
  save_path: /content/drive/My Drive/RANZCR/weights/resnet_200D/6th-Mar-V1
  model_weight_path_folder: /content/drive/My Drive/pretrained-weights/pretrained-resnet200D-weights
model_factory: timm
model_name: resnet200d
device: auto
augmentations_class: Albumentations
augmentations_train:
  AlbumentationsAugmentation:
    - name: VerticalFlip
      params:
        p: 0.5
    - name: HorizontalFlip
      params:
        p: 0.5
    - name: RandomBrightness
      params:
        limit: 0.2
        p: 0.75
    - name: RandomContrast
      params:
        limit: 0.2
        p: 0.75
    - name: HueSaturationValue
      params:
        hue_shift_limit: 10
        sat_shift_limit: 10
        val_shift_limit: 10
        p: 0.5
    - name: ShiftScaleRotate
      params:
        shift_limit: 0.1
        scale_limit: 0.1
        rotate_limit: 15
        border_mode: 0
        p: 0.85
    - name: Resize
      params:
        height: 256
        width: 256
        p: 1.0
    - name: Normalize
      params:
        p: 1.0
    - name: ToTensorV2
      params:
        p: 1.0
augmentations_val:
  AlbumentationsAugmentation:
    - name: Resize
      params:
        height: 256
        width: 256
        p: 1.0
    - name: Normalize
      params:
        p: 1.0
    - name: ToTensorV2
      params:
        p: 1.0

