seed: 1930
num_workers: auto # 0 when using from Windows 
num_classes: 11
class_list:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
train_batch_size: 32
val_batch_size: 64
n_epochs: 16
scheduler: CosineAnnealingWarmRestarts
scheduler_params:
  StepLR:
    step_size: 2
    gamma: 0.3
    last_epoch: -1
    verbose: True
  ReduceLROnPlateau:
    mode: max
    factor: 0.7
    patience: 2
    threshold: 0.01
    threshold_mode: rel
    cooldown: 0
    min_lr: 1.e-5
    eps: 1.e-8
    verbose: True
  CosineAnnealingWarmRestarts:
    T_0: 16
    T_mult: 1
    eta_min: 0
    last_epoch: -1
    verbose: True    
train_step_scheduler: False
val_step_scheduler: True
optimizer: AdamW
optimizer_params:
  AdamW:
    lr: 2.5e-04
    betas:
      - 0.9
      - 0.999
    eps: 1.e-8
    weight_decay: 1.e-3
    amsgrad: False
  Adam:
    lr: 1.e-4
    betas:
      - 0.9
      - 0.999
    eps: 1.e-8
    weight_decay: 1.e-6
    amsgrad: False
criterion_train: BCEWithLogitsLoss
criterion_val: BCEWithLogitsLoss
criterion_params:
  CrossEntropyLoss:
    weight: null
    size_average: null
    ignore_index: -100
    reduce: null
    reduction: mean
  LabelSmoothingLoss:
    classes: 2
    smoothing: 0.05
    dim: -1
  FocalCosineLoss:
    alpha: 1
    gamma: 2
    xent: 0.1
use_amp: True
debug: False
cv_schema: RepeatedStratifiedGroupKFold
classification_type: MultiLabel
result_params:
  average_loss: {}
  multi_class_roc_auc_score: {}
  val_preds_softmax_array: {}
results_train:
  - average_loss
results_val:
  - average_loss
  - val_preds_softmax_array
  - multi_class_roc_auc_score
monitored_result: multi_class_roc_auc_score
image_size: 640
verbose: 1
verbose_step: 1
num_folds: 5
image_col_name: StudyInstanceUID
class_col_name:
  - ETT - Abnormal
  - ETT - Borderline
  - ETT - Normal
  - NGT - Abnormal
  - NGT - Borderline
  - NGT - Incompletely Imaged
  - NGT - Normal
  - CVC - Abnormal
  - CVC - Borderline
  - CVC - Normal
  - Swan Ganz Catheter Present
group_kfold_split: PatientID
paths:
  log_path: /content/drive/My Drive/RANZCR/weights/densenet/10th-Mar-V1/log.txt
  train_path: /content/train/train
  csv_path: /content/df_folds.csv
  save_path: /content/drive/My Drive/RANZCR/weights/densenet/10th-Mar-V1
  model_weight_path_folder: /content/drive/My Drive/pretrained-weights/pretrained-densenet-weights
  custom_pretrained_weight: /content/drive/My Drive/pretrained-weights/pretrained-densenet-weights/densenet121_chestx.pth
model_factory: timm
model_name: resnet200d
device: auto
augmentations_class: AlbumentationsAugmentation
augmentations_train:
  AlbumentationsAugmentation:
    - name: HorizontalFlip
      params:
        p: 0.5
    - name: ShiftScaleRotate
      params:
        shift_limit: 0.2
        scale_limit: 0.2
        rotate_limit: 20
        border_mode: 0
        value: 0
        mask_value: 0
        p: 0.5
    - name: RandomResizedCrop
      params:
        height: 512
        width: 512
        scale: [0.9, 1.0]
        p: 1.0
    - name: Cutout
      params: 
        max_h_size: 51
        max_w_size: 51
        num_holes: 5
        p: 0.5
    - name: Normalize
      params:
        mean: [0.4887381077884414]
        std: [0.23064819430546407]
        p: 1.0
    - name: ToTensorV2
      params:
        p: 1.0
augmentations_val:
  AlbumentationsAugmentation:
    - name: Resize
      params:
        height: 512
        width: 512
        p: 1.0
    - name: Normalize
      params:
        mean: [0.4887381077884414]
        std: [0.23064819430546407]
        p: 1.0
    - name: ToTensorV2
      params:
        p: 1.0

