seed: 1930
num_classes: 2
batch_size: 32
n_epochs: 8
lr: 0.001
scheduler: CosineAnnealingWarmRestarts
train_step_scheduler: False
val_step_scheduler: True
T_0: 10
min_lr: 1.e-6
weight_decay: 1.e-6
image_size: 256
resize: 256
crop_size:
  128: 110
  256: 200
  512: 400
verbose: 1
verbose_step: 1
num_folds: 5
image_col_name: image_name
class_col_name: target
log_path: ./log.txt
train_path: ../input/jpeg-melanoma-256x256/train
csv_path: ../input/siim-isic-melanoma-classification/train.csv
save_path: ./
effnet: tf_efficientnet_b2_ns
device: cuda
model_weight_path_folder: ../input/efficientnet-weights
